
// index-like file
// this is a CSV file with the following columns:
// info, lane, read1, read2
params.fqindex = "index.csv"

// reference genome
params.genome = "genome.fa"
params.fai = "genome.fa.fai"
params.gzi = null

// this will be used within the mapping workflow
// IMPORTANT, this needs to be generated by BWA2!
params.bwa2index = null
params.minibwaindex = null
params.skip_bwa2 = false
params.skip_minibwa = false

include { FQPP } from './workflows/fqprocess'
include { MAP } from './workflows/mapping'
include { POSTMAPPING } from './workflows/postmapping'

workflow  {
    fasta_file = file(params.genome)
    fai_file = file(params.fai)
    gzi_file = params.gzi ? file(params.gzi) : params.genome.endsWith('.gz') ? file("${params.genome}.gzi") : []

    fq_ch = Channel.fromPath(params.fqindex) \
        | splitCsv(header:true) \
        | map { row-> tuple(row.info, row.lane, file(row.read1), file(row.read2)) } \
        | map {
            info, lane,read1, read2 -> 
                def meta = [:]
                def tokens = info.split(":")
                tokens.each { tok ->
                    def to = tok.split("=")
                    meta[to[0]] = to[1]
                }
            tuple(meta, lane, read1, read2)
        } 
    
    FQPP(fq_ch)
    // params.bwaindex is needed here too!
    MAP(
        FQPP.out.fqreads,
        fasta_file,
        fai_file,
        gzi_file
    )

    POSTMAPPING(
        MAP.out.mapped,
        fasta_file,
        fai_file
    )

}
